### ISSUE TITLE
Uncaught TypeError: util.promisify requires a true ES5 environment, that also supports `__proto__`

### ISSUE THREAD

**Issue by talentlessguy** [jspm/project#131]
When trying to import [@ethereumjs/vm](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm):

```ts
import vm from 'https://dev.jspm.io/@ethereumjs/vm'
```

I get this:

```
Uncaught TypeError: util.promisify requires a true ES5 environment, that also supports `__proto__`
    at dew (https://dev.jspm.io/npm:util.promisify@1.1.1/implementation.dew.js:17:11)
    at dew (https://dev.jspm.io/npm:util.promisify@1.1.1/index.dew.js:16:24)
    at dew (https://dev.jspm.io/npm:@ethereumjs/vm@5.5.3/dist.browser/index.dew.js:280:19)
    at https://dev.jspm.io/@ethereumjs/vm:2:16
```

**Comment by guybedford** [comment]
What environment are you running in? Deno? If so I would suggest using the Deno import map version that will link against the Deno standard libraries - see https://generator.jspm.io/#6+JhYGBk9M1PKc1JLWZwSC3JSC1KLc3NKtYvy3Uw1TPVMwYA9UiXwCIA.

**Comment by talentlessguy** [comment]
@guybedford yes it's Deno

**Comment by guybedford** [comment]
You can read more on the Deno support in https://jspm.org/docs/workflows#deno.

**Comment by guybedford** [comment]
> and the link you sent doesn't seem to be working

I actually had to fix some issues to get it to work - make sure to clear your browser cache.
