### ISSUE TITLE
Package Issue - @emotion/styled@11.6.0

### ISSUE THREAD

**Issue by giltayar** [jspm/project#170]
```
JspmError: Unable to request the JSPM API for a build of npm:@emotion/styled@11.6.0, with error: Package @emotion/styled@11.6.0 has already been built by JSPM. If there is a build issue, please post a bug report to https://github.com/jspm/project/issues/new?title=Package%20Issue%20-%20%40emotion%2Fstyled%4011.6.0., 401.
    at ensureBuild (file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:257:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Resolver.resolveLatestTarget$1 (file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:292:13)
    at async Resolver.resolveLatestTarget (file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:1250:21)
    at async Installer.installTarget (file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:589:24)
    at async TraceMap.trace (file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:1811:189)
    at async file:///Users/giltayar/code/mono/packages/commons-frontend/template-template-react-component/node_modules/@jspm/generator/dist/generator.js:1639:46
```

**Comment by guybedford** [comment]
Thanks for posting, the gzip service has had reliability issues recently with growth. I've since upgraded its capacity and am looking into why the health check failed. Should all be working now.

**Comment by guybedford** [comment]
Finished up a couple of fixes to avoid this in future, with a new server health check and using brotli in the generator by default (which is the optimized path on the CDN). A generator update will roll this out shortly.
