### ISSUE TITLE
500 Internal Server Error #17 7.073     at https://dev.jspm.io/npm:tarn@3.0.2/dist/Pool.dew.js:5:21

### ISSUE THREAD

**Issue by slim-hmidi** [jspm/project#201]
I'm using Deno v 1.21.3 and I'm trying to build a docker image for my application:
``` 
FROM ubuntu:20.04

# install curl
RUN apt-get update && apt-get install -y curl unzip sudo nginx

# install deno v1.21.3
RUN curl -fsSL https://deno.land/install.sh | sh -s v1.21.3

ENV DENO_INSTALL="/root/.deno"
ENV PATH="${DENO_INSTALL}/bin:${PATH}"


# The working directory of the project
WORKDIR /app


# Copy the backend directory
RUN mkdir backend
COPY backend/deps.ts ./backend/deps.ts 
RUN cd ./backend && deno cache --unstable deps.ts

....
```
my deps.ts:
```ts
// fmt
export {
  bold,
  cyan,
  green,
  red,
} from "https://deno.land/std@0.114.0/fmt/colors.ts";

// flags
export { parse } from "https://deno.land/std@0.120.0/flags/mod.ts";

// oak
export { Application } from "https://deno.land/x/oak@v10.5.1/mod.ts";
export {
  Context,
  helpers,
  isHttpError,
  Router,
  Status,
} from "https://deno.land/x/oak@v10.5.1/mod.ts";
export type { ErrorStatus } from "https://deno.land/x/oak@v10.5.1/mod.ts";

// computed_types
export {
  number,
  Schema,
  string,
  unknown,
} from "https://denoporter.sirjosh.workers.dev/v1.1.0/deno.land/x/computed_types/src/index.ts";
export type { ResolvedValue } from "https://denoporter.sirjosh.workers.dev/v1.1.0/deno.land/x/computed_types/src/index.ts";
export type { ValidationError } from "https://denoporter.sirjosh.workers.dev/v1.1.0/deno.land/x/computed_types/src/index.ts";

// inject
export {
  bootstrap,
  Bootstrapped,
  Injectable,
} from "https://deno.land/x/inject@v0.1.2/mod.ts";

// denodb
export {
  Database,
  DataTypes,
  Model,
  PostgresConnector,
  Relationships,
} from "https://deno.land/x/denodb@v1.0.40/mod.ts";
export type { Connector } from "https://deno.land/x/denodb@v1.0.40/mod.ts";
export type { Values } from "https://deno.land/x/denodb@v1.0.40/lib/data-types.ts";

//bcrypt
export * as bcrypt from "https://deno.land/x/bcrypt@v0.2.4/mod.ts";

//djwt
export {
  create as sign,
  getNumericDate,
  verify,
} from "https://deno.land/x/djwt@v2.4/mod.ts";
export type { Header } from "https://deno.land/x/djwt@v2.4/mod.ts";
export { OAuth2Client } from "https://deno.land/x/oauth2_client@v0.2.1/mod.ts";
// dotenv
export { config as env } from "https://deno.land/x/dotenv@v3.2.0/mod.ts";

// dotenv
export { expect } from "https://deno.land/x/expect@v0.2.9/mod.ts";

// superoak
export { superoak } from "https://deno.land/x/superoak@4.6.0/mod.ts";

// oak_cors
export { CORS } from "https://deno.land/x/oak_cors@v0.1.1/mod.ts";
```
I got this error, while the build reach this instruction `RUN cd ./backend && deno cache --unstable deps.ts`:
```
error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error
#17 7.073     at https://dev.jspm.io/npm:tarn@3.0.2/dist/Pool.dew.js:5:21
------
executor failed running [/bin/sh -c cd ./backend && deno cache --unstable deps.ts]: exit code: 1
```
How can I fix that?

**Comment by guybedford** [comment]
`dev.jspm.io` is the old server. It is better to use the import map generation against `ga.jspm.io` or to use `jspm.dev`.
